version: "1"
rules:
  - base: master
    upstream: waleks647:master
    mergeMethod: merge
    conflictReviewers:
      - weiii-joe
      - xhuanfux
      - xMikux
  - base: master
    upstream: Sefiraat:master
    mergeMethod: merge
    conflictReviewers:
      - weiii-joe
      - xhuanfux
      - xMikux
